name: Build Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install ARM Toolchain
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10-2020-q4' 
        
    - name: Set Environment Variables
      run: sh ./set_environment.sh
        
    - name: Patch MD Libraries
      run: sh ./patch-linux.sh
        
    - name: Make all
      run: make all
