name: Build Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install ARM Toolchain
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10-2020-q4' 
        
    - name: Set Environment Variables
      run: sh ./set_environment.sh
        
    - name: Patch MD Libraries
      run: sh ./patch-linux.sh
      
    - name: Install Prerequisites
      run: sudo apt-get install make unrar-free autoconf automake libtool gcc g++ gperf flex bison texinfo gawk ncurses-dev libexpat-dev python-dev python python-serial sed git unzip bash help2man wget bzip2
      
    - name: Build Open ESP SDK
      run: cd esp-open-sdk && make
      
    - name: Make all
      run: make all
